FyndApp/urls.py
from django.conf.urls import url
from FyndApp.Views.dashboard import dashboard,view_movies_deatils,search_movies
from FyndApp.Views.addmovies import movies,movie_edit
from FyndApp.Views.loginpage import signup,logout_user,login_user

app_name="FyndApp"

urlpatterns = [
    url(r'^$', dashboard, name='dashboard'),
    url(r'^movies/$', movies, name='movies'),
    url(r'^movie/(?P<pk>\w+)/view/$', view_movies_deatils, name='view_movies_deatils'),
    url(r'^search/$', search_movies, name='search_movies'),
    url(r'^movie/(?P<idd>\w+)/edit/$', movie_edit, name='movie_edit'),
    url(r'^signup/$', signup, name='signup'),
    url(r'^logout/$', logout_user, name='logout_user'),
    url(r'^login/$', login_user, name='login_user'),





]

FyndProject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('FyndApp.urls', namespace='FyndApp')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

FyndApp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Movies(models.Model):
    """ Movies Model Fields"""
    name = models.CharField(max_length=200, null=True)
    director = models.CharField(max_length=200, null=True)
    genre = models.CharField(max_length=1000, null=True)
    score = models.FloatField(null=True)
    popularity = models.FloatField(null=True)
    image = models.ImageField(upload_to=None, default='no-img.jpg', null=True)
    release_date = models.DateField(null=True)
    country = models.CharField(max_length=200, null=True)
    language = models.CharField(max_length=200, null=True)
    storyline = models.TextField(null=True)
    cast = models.TextField(null=True)
    youtube = models.URLField(null=True)

    def __unicode__(self):
        return str(self.name)
        

FyndApp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

FyndApp/templates/_partials/_addmovies.html
{% if movie_obj %}
{% for movie in movie_obj%}
<tr id="tr_{{movie.id}}">
    <td>{{movie.name}}</td>
    <td>{{movie.director}}</td>
    <td>{{movie.popularity}}</td>
    <td>{{movie.score}}</td>   
    <td>{{movie.genre}}</td>
    <td data-value="{{movie.id}}"><a href="#" class="tooltipped movie_edit" data-position="bottom" data-delay="50"
            data-tooltip="moviedetails"><i  class="material-icons dp48 get_movie" >mode_edit</i></a></td>
    <td data-value="{{movie.id}}"><a href="#" class="tooltipped delete_movie" data-position="bottom" data-delay="50"
            data-tooltip="delete movie"><i class="material-icons dp48 " >delete</i></a></td>
</tr>
{% endfor %}
{% else %}
<tr style="border:none">
        <td colspan="7" class="center-align"><strong style="font-style: italic">No movies found.....</strong> </td>
    </tr>
{% endif %}

FyndApp/templates/_partials/_preloader.html
<div class="pl">
        <div class="preloader-wrapper big">
            <div class="spinner-layer spinner-blue-only">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="gap-patch">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
    </div>

FyndApp/templates/dashboard.html
{% extends 'index.html' %} {% block content %}
<div class="col s12 m12 l12 ">
    <div class='row-pad messagebox'>
        <div class='col s12' style="margin-bottom: 20px;">
            <p class="center-align" id="message"></p>
        </div>
    </div>

  <div class="row">
    <br>
    <div class="col s12 m12 l6 ">
      <div class="card-title left-align">
        <h2>Upcoming Movies</h2>
      </div>
      <section class="card-content ">
            <div class="carousel">
                    {% for upcoming in upcomobj%}
                    <a class="carousel-item" href="{% url 'FyndApp:view_movies_deatils' pk=upcoming.id %}"><img src="static/images/{{upcoming.image}}"></a>
                    {% endfor %}
            </div>
      </section>
    </div>
    <div class="col s12 m12 l6 ">
            <div class="card-title left-align">
              <h2>Now Playing (Box Office)</h2>
            </div>
            <section class="card-content ">
                  <div class="carousel">
                        {% for nowplay in nowplayobj%}
                        <a class="carousel-item" href="{% url 'FyndApp:view_movies_deatils' pk=nowplay.id %}"><img src="static/images/{{nowplay.image}}"></a>
                        {% endfor %}
                  </div>
            </section>
          </div>
  </div>
</div>



<style>
  .card-pad,
  .card-content {
    background-color: white;
  }

  .card-title {
    background-color: ghostwhite;
    height: 45px;
    padding: 15px 0px 0px 10px;
  }

  .card-content {
    width: auto;
    height: 400px;
  }

  h1 {
    padding-top: 20px;
  }


  
</style>
<script>
        $(document).ready(function(){
            $('.carousel').carousel();
          });
          
          {% if messages %}
          {% for msg in messages %}
              $('#message').html('{{msg}}').addClass('{{msg.tags}}')
              Materialize.toast('{{msg}}', 5000)
          {% endfor %}
      {% endif %}
  
</script>
{% endblock %}

FyndApp/templates/index.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <title>GoFynd-Movies </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--<link type="text/css" rel="stylesheet" href="/css/main.css" media="screen" />-->
    <!--<script src="/static/js/util.js" type="text/javascript"></script>-->
    <script type="text/javascript" src="{% static "js/jquery-3.2.1.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/materialize.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/jquery.nicescroll.js" %}"></script>
    <script type="text/javascript" src="{% static "js/gistfile1.js" %}"></script>
    <script type="text/javascript" src="{% static "js/jquery.materialize-autocomplete.js" %}"></script>
    <script type="text/javascript" src="{% static "js/moment.min.js" %}"></script>
    <!-- <script type='text/javascript' src='/cdn.jsdelivr.net/jquery.marquee/1.3.9/jquery.marquee.min.js'></script> -->
    <script type="text/javascript" src="{% static "js/script.js" %}"></script>
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static "css/materialize.min.css" %}" media="screen,projection" />
    <link type="text/css" rel="stylesheet" href="{% static "css/materializestyle.css" %}" />
    <!-- <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" /> -->
    <style>
        .pl {
            display: flex;
            align-items: center;
            justify-content: center;
            background-color: lightgray;
            position: fixed;
            z-index: 9999;
            opacity: .7;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
        }
        
        .brand-logo {
            height: 50px;
            width: 150px;
            background-position: cover;
        }
        
        .logo-img {
            height: 50px;
        }
         .disableclick{
            cursor: text;
            pointer-events: none;
            color: lightgray;
        }
        ::-webkit-scrollbar {
            width: 7px;
            color: black
        }

        ::-webkit-scrollbar-track {
            -webkit-box-shadow: inset  5px rgba(0,0,0,0.5);
            box-shadow: inset 5px rgba(0,0,0,0.5);
        }

        ::-webkit-scrollbar-thumb {
            -webkit-box-shadow: inset 0 0 5px rgba(0,0,0,0.6); 
            box-shadow: inset 0 0 5px rgba(0,0,0,0.6); 
        }
        textarea.materialize-textarea{
                padding: 0rem 0 1.6rem 0 !important;
        }
        .inline-flex{
            display: inline-flex;
        }
        .icon_fix-1 {
            font-size: 22px;
        }
        .icon_text_fix-1 {
            margin-left: 13px;
        }
        .m-top-1{
            margin-top:70% !important;
        }
        .m-top-11{
            margin-top:85%
        }
    </style>
    <script type="text/javascript">
        function isNotEmpty(val) {
            if (val.match(/^s+$/) || val == "") {
                return false;
            } else {
                return true;
            }
        }

        // To change the active side bar element
        $(document).on('ready', function () {
            //var logo = Cookies['logo']
            //$('.logo-img').attr('src',Cookies['logo'].replace(/"/g,''))
            var url = location.pathname
            var links = $('li a')
            $('ul li ').removeClass('active')
            links.each(function () {
                if ($(this).attr('href') == url) {
                    $(this).parent().addClass('active')
                }
            })
        })

        // END
    </script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script>
        !function(e,n,t,r){
            function o(){try{var e;if((e="string"==typeof this.response?JSON.parse(this.response):this.response).url){var t=n.getElementsByTagName("script")[0],r=n.createElement("script");r.async=!0,r.src=e.url,t.parentNode.insertBefore(r,t)}}catch(e){}}var s,p,a,i=[],c=[];e[t]={init:function(){s=arguments;var e={then:function(n){return c.push({type:"t",next:n}),e},catch:function(n){return c.push({type:"c",next:n}),e}};return e},on:function(){i.push(arguments)},render:function(){p=arguments},destroy:function(){a=arguments}},e.__onWebMessengerHostReady__=function(n){if(delete e.__onWebMessengerHostReady__,e[t]=n,s)for(var r=n.init.apply(n,s),o=0;o<c.length;o++){var u=c[o];r="t"===u.type?r.then(u.next):r.catch(u.next)}p&&n.render.apply(n,p),a&&n.destroy.apply(n,a);for(o=0;o<i.length;o++)n.on.apply(n,i[o])};var u=new XMLHttpRequest;u.addEventListener("load",o),u.open("GET","https://"+r+".webloader.smooch.io/",!0),u.responseType="json",u.send()
        }(window,document,"Smooch","57f53520b24654f600c022a9");
    </script>
</head>

<body>
        {%include '_partials/_preloader.html' %}
    <div class="overlay">
        <header class="navbar-fixed">
            <nav>
                <div class="nav-wrapper">
                    <div class="logo-wrapper">
                        <div class="sprite-menu hamburger" style="margin-top:5px;">
                            <a href="#" class="sprite"></a>                            
                        </div>
                        <a href="{% url 'FyndApp:dashboard' %}" class="brand-logo">
                            <img class="logo-img" src="/static/images/None/fynd_logo .png"
                            style="max-width:150px;"></a>

                        
                        <span class="company-name hide-on-med-and-down">
                                <div class="col m12 s12 l6">
                                        <div class="input-field col m12 s12 l12">
                                            <div class="autocomplete">
                                                <div class="ac-input">
                                                    <ul class="ac-scust ac-appender">
                                                        <input type="text" name="txtsearch_moive" id="txtsearch_movie" 
                                                        required data-activates="sourcemovies" style="width:500px;">
                                                        <ul id="sourcemovies" class="dropdown-content ac-dropdown"></ul>
                                                        <label for="txtsearch_movie">Search movies here.....</label>
                                                    </ul>
                                                </div>
                                            </div>

                                        </div>
                                        <!-- <button class="waves-effect waves-light btn" type="button" id="search_btn" name="search_btn">Go</button> -->

                                        <!-- <div class="input-field col m12 s12 l3" style=" margin-top: 27px;"> -->
                                             <!-- </div> -->
                                    </div>
                               
                            
                        </span>
                    </div>
                    
                    <ul id="nav-mobile" class="right">
                            {% if not user.is_authenticated %}
                            <li style="width:105px;padding-top:15px">
                                <a href="{% url 'FyndApp:signup' %}">
                                    <h2>Signup</h2>
                                </a>
                            </li>

                            <li style="padding-top:15px">
                                <a href="{% url 'FyndApp:login_user' %}">
                                    <h2>Login</h2>
                                </a>
                            </li>
                            {% endif %}

                        {% if user.is_authenticated %}
                        <li class="user-name">                            
                            <a href="#">
                                <div class="user-pic circle">
                                    <!-- <img src="{%if request.session.profile_pic%}{{request.session.profile_pic}}{%else%}{%endif%}" alt="user name"> -->
                                </div>
                                <h3 class="hide-on-med-and-down">Logged in as <span>{{ request.user.first_name }}</span>
                                </h3>
                            </a>
                        </li>
                        <li class="sprite-logout">
                            <a class="sprite" href="{% url 'FyndApp:logout_user'%}"></a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>
        <section id="main-body">
            <div class="row zero-margin-bottom pos">
                <div class="side-navBar" id="right-nav">
                    <ul class="nav-ul zero-margin">
                            {% if request.user.is_superuser %}

                                <li>
                            <a href="{% url 'FyndApp:movies' %}" class="inline-flex" >
                                <i class="material-icons icon_fix-1">note_add</i>
                                <span class="icon_text_fix-1">Add Movies</span>
                            </a>
                        </li>
                        {% endif %}

                    </ul>
                </div>
                <div class="left-container margin-278" id="content-placeholder">
                    <!-- put yor content pages here -->
                    {% block content %} {% endblock %}
                </div>
            </div>
        </section>


    </div>
    <script>
       var lis =  document.querySelectorAll('#right-nav ul li').length
       if (lis >= 9){
            $('li.hide-on-med-and-down:first').removeClass('m-top-1')
       }else{
        $('li.hide-on-med-and-down:first').addClass('m-top-1')
       }
        Smooch.init({ appId: '57f53520b24654f600c022a9' })


    movieSelect = $("#txtsearch_movie").materialize_autocomplete({
            multiple: {
                enable: false
            },
            appender: {
                el: '.ac-scust'
            },
            dropdown: {
                el: '#sourcemovies',
                itemTemplate: '<li class="ac-scust" data-id="<%= item.id %>" data-text=\'<%= item.value %>\'><a ><%= item.value %>(<%= item.year %>)<br><span style="color:black;font-size: 13px;">\
                    <%=item.director %> |<%= item.genre %> | <%= item.language %></span></a></li>'
            },
            showListOnFocus: false,
            minLength: 1,
            getData: function (value, callback) {
                $('#sourcemovies').html('')
                getMovies(value, callback);
            },
    
            onSelect: function (item) {
                debugger
                url = '{% url "FyndApp:view_movies_deatils" pk=4%}'.replace('4',item.id)
                window.location.href = url

            }
        })
    
    
    
        function getMovies(term, callback) {
            var cache = {}
            if (term in cache) {
                response(cache[term]);
                return;
            }
            $.ajax({
                url: '{% url "FyndApp:search_movies" %}',
                datatype: 'json',
                method: 'GET',
                data: {
                    'term': term
                },
                success: function (data) {
                    debugger
                    if (typeof data.error != 'undefined') {
                        console.log('invalid search')
                        data = []
                    }
                    callback(term, JSON.parse(data))
                }
            })
        }
    
    </script>

</body>
</html>

FyndApp/templates/loginpage.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta content="text/html; charset=UTF-8" http-equiv="content-type" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <script src="{% static 'js/security.js' %}"></script>
    <script type="text/javascript" src="{% static "js/jquery-3.2.1.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/materialize.min.js" %}"></script>
    <!--Import materialize.css-->

    <link type="text/css" rel="stylesheet" href="{% static "css/materialize.min.css" %}" media="screen,projection" />
    <link type="text/css" rel="stylesheet" href="{% static "css/materializestyle.css" %}" />

    <style>
        .error {
            color: #e53935
        }

        .success {
            color: #4caf50
        }
        .loginbody{
            background-repeat: no-repeat;
            background-size: cover
        }

        @media(min-width: 360px)and (max-width: 384px) {
            .centered {
                position: inherit;
                width: 90%;
                margin: 0 auto;
                margin-top: 25%;
            }
        }

        @media(min-width: 385px) and (max-width: 411px) {
            .centered {
                position: inherit;
                width: 90%;
                margin: 0 auto;
                margin-top: 15%;
            }
        }

        @media(min-width: 412px) and (max-width: 419px) {
            .centered {
                position: inherit;
                width: 90%;
                margin: 0 auto;
                margin-top: 30%;
            }
        }

        @media(min-width: 420px) and (max-width: 600px) {
            .centered {
                position: inherit;
                width: 60%;
                padding-top: 45%;
                margin: 0 auto;
            }
        }

        @media(min-width: 601px)and (max-width: 799px) {
            .centered {
                position: absolute;
                top: 20%;
                left: 50%;
                padding-top: initial;
                transform: translateY(-50%);
                transform: translateX(-50%);
            }
        }

        @media(min-width: 800px) {
            .centered {
                position: absolute;
                top: 20%;
                left: 50%;
                padding-top: initial;
                transform: translateY(-50%);
                transform: translateX(-50%);
            }
        }

        @media only screen and (min-width: 990px) {
            .centered {
                position: inherit;
                margin: 0 auto;
                width: 32%;
                padding-top: 5%;
                max-height: 30%;
                transform: inherit;
                padding-bottom: 3%;

            }
        }
        /*Fixing the background */

        html {
            /*position: fixed; */
            top: 0;
            left: 0;
            min-width: 100%;
            min-height: 100%;
        }

        .label-align {
            margin-left: -12px;
        }

        .h4 {
            font-size: 1em;
            margin: 1.33em 0;
        }

        body {
            background-color: inherit
        }

        .messagebox {
            padding-top: 10px
        }

        {% if showcaptcha %}

        .recaptcha-wrapper {
            overflow: hidden;
            background-color: #F9F9F9;
            border-radius: 3px;
            box-shadow: 0px 0px 4px 1px rgba(0, 0, 0, 0.08);
            -webkit-box-shadow: 0px 0px 4px 1px rgba(0, 0, 0, 0.08);
            -moz-box-shadow: 0px 0px 4px 1px rgba(0, 0, 0, 0.08);
            height: 70px;
            position: relative;
            margin-top: 17px;
            border: 1px solid #d3d3d3;
            color: #000;
        }

        .recaptcha-info {
            background-size: 32px;
            height: 32px;
            margin: 0 13px 0 13px;
            position: absolute;
            right: 8px;
            top: 9px;
            width: 32px;
            background-image: url(https://www.gstatic.com/recaptcha/api2/logo_48.png);
            background-repeat: no-repeat;
        }

        .rc-anchor-logo-text {
            color: #9b9b9b;
            cursor: default;
            font-family: Roboto, helvetica, arial, sans-serif;
            font-size: 10px;
            font-weight: 400;
            line-height: 10px;
            margin-top: 5px;
            text-align: center;
            position: absolute;
            right: 10px;
            top: 37px;
        }

        .rc-anchor-checkbox-label {
            font-family: Roboto, helvetica, arial, sans-serif;
            font-size: 14px;
            font-weight: 400;
            line-height: 17px;
            left: 50px;
            top: 26px;
            position: absolute;
            color: black;
        }

        .rc-anchor .rc-anchor-normal .rc-anchor-light {
            border: none;
        }

        .rc-anchor-pt {
            color: #9b9b9b;
            font-family: Roboto, helvetica, arial, sans-serif;
            font-size: 8px;
            font-weight: 400;
            right: 10px;
            top: 53px;
            position: absolute;
        }

        .rc-anchor-pt a:link {
            color: #9b9b9b;
            text-decoration: none;
        }

        .g-recaptcha {
            width: 41px;
            /* border: 1px solid red; */
            height: 38px;
            overflow: hidden;
            float: left;
            margin-top: 16px;
            margin-left: 6px;
        }

        .g-recaptcha>div {
            width: 46px;
            height: 30px;
            /*background-color: #F9F9F9;*/
            overflow: hidden;
            border: 1px solid red;
            transform: translate3d(-8px, -19px, 0px);
        }

        .g-recaptcha div {
            border: 0;
        }

        {% endif %}

        .socialimg {
            height: 34px;
        }

        .responsive-img {
            max-width: 86% !important;
        }

        .white {
            margin-top: -34px;
            opacity: 0.9;
        }
    </style>
</head>

<body class="loginbody">
    <!--{%include '_partials/_preloader.html' %}-->
    <div class="centered">
        <div class="white s10 l4 m10 ">
            <div style="padding: 32px 36px 0px 36px; border: 1px solid #EEE;">
                <div class="center">
                    <img class="responsive-img " style="margin-bottom:10px;max-height: 100px;width: auto" src="/static/images/None/fynd_logo .png"
                    />
                </div>
                <div class='row-pad messagebox'>
                    <div class='col s12' style="margin-bottom: 20px;">
                        <p class="center-align" id="message"></p>
                    </div>
                </div>
                <form class="col s12" method="post" action="{% url 'FyndApp:login_user' %}" id="loginform">{% csrf_token %}

                    <div class='row-pad'>        
                        <div class="col m12 s12 l12">
                            <div class='input-field col l12 s12'>
                                <input name="username" tabindex="1" class='validate' type='email' name='username' id='email' title="Email" />
                                <label for='email' class="label-align active">Enter your email</label>
                            </div>
                        </div>
                    </div>
                    <div class='row-pad'>
                        <div class="col m12 s12 l12">
                            <div class='input-field col l12 s12'>
                                <input class='validate' tabindex="2" name='password' id='password' type="password" title="Password" value="" />
                                <label for='password' class="active label-align">Enter your password</label>
                            </div>
                        </div>
                    </div>    
                    <br />
                    <center>
                        <div class='row'>
                            <button type='submit' tabindex="3" style="height: 45px" name='btn_login' class='col s12 btn btn-large waves-effect '>Login</button>
                        </div>
                    </center>
                </form>
            </div>
        </div>
    </div>
</body>
<script>
    $(document).ready(function () {
        $('.tooltipped').tooltip({
            delay: 50
        });
    });
    $(function () {
        $.ajax({
            url: "https://perk.brio.co.in/api/BingImageURL",
            datatype: "json",
            success: function (data) {
                $('.loginbody').css('background-image', 'url(' + data[0].bingURL + ')', 'opacity', '1');
            }
        });
    })

    {% if messages %}
        {% for msg in messages %}
            $('#message').html('{{msg}}').addClass('{{msg.tags}}')
            Materialize.toast('{{msg}}', 5000)
        {% endfor %}
    {% endif %}
    //document.getElementById('token').value = new Fingerprint().get();
    var social = [
        'adn',
        'bitbucket',
        'dropbox',
        'facebook',
        'flickr',
        'foursquare',
        'github',
        'google',
        'instagram',
        'linkedin',
        'windows ',
        'odnoklassniki',
        'openid',
        'pinterest',
        'reddit',
        'soundcloud',
        'tumblr',
        'twitter',
        'vimeo',
        'vk',
        'yahoo'
    ]
    var buttons = '';
    $.each(social, function (index, network) {
        buttons += '<div class="row usage ' + network + '"><a class="waves-effect waves-light btn social col s12 ' + network + '"><i class="fa fa-fw fa-' + network + '"></i> Sign in with ' + network + '</a></div>'
    });
    $('.all').html(buttons);
    var current = 'google';
    $('.usage').on('mouseenter', function () {
        var icon = $(this).attr('class').replace('row usage ', '');
        var regex = new RegExp(current, "gi");
        $('.examples').html(function (index, html) {
            return html.replace(regex, icon);
        });
        current = icon;
    })
        //$('.example').html(html)

</script>

</html>

FyndApp/templates/movieview.html
{% extends 'index.html' %} {% block content %}
<div class="col s12 m12 l12 ">
  <div class="row" style="background-color:#333">
    <br>
    <div class="card-title left-align">
            <div class="col s12 m12 l7">
                    <h2 style="font-size:40px;">{{movieobj.name}}({{movieobj.release_date|date:'Y'}})</h2> 
                    <span>1h 30min</span>|<span> {{movieobj.genre}}</span>|<span>   {{movieobj.release_date|date:'d M Y'}} ({{movieobj.country}})</span>

                </div>
                 <div class="col s12 m12 l1" style="text-align: right !important;">
                        <h2 style="font-size:25px;">{{movieobj.score}}/10</h2>
                     </div>
            <!-- <div class="row"> -->
            <!-- </div> -->
    </div>
    
    <div class="col s12 m12 l2 ">
      <section class="card-content " style="height:287px;">
            <img class="responsive-img" src="/static/images/{{movieobj.image}}" style="width:215px;height:286px;">
      </section>
    </div>
    <div class="col s12 m12 l6 ">
            <section class="card-content ">
                    <div class="video-container">
                            <iframe width="853" height="400  " 
                    src="{{movieobj.youtube}}" frameborder="0" allowfullscreen ></iframe>
                          </div>

            </section>
    </div>
    <div class="col s12 m12 l4"></div>
        
  </div>
  <div class="col s12 m12 l8">
  <div class="row">
      <div class="col s12 m12 l12">
            Director: <a href="#">{{movieobj.director}}</a>
      </div>
  </div>
  <div class="row">
      <div class="col s12 m12 l12">
            Writers: <a href="#">
                    Dorothy Blyskal (screenplay by)
            </a>
      </div>
  </div>
  <div class="row">
        <div class="col s12 m12 l12">
                Stars: <a href="#">
                        Alek Skarlatos, Anthony Sadler, Spencer Stone
                </a>
        </div>
    </div>  
<div class="row">
        <div class="col s12 m12 l12">
                <h2>Storyline</h2>
        </div>
    </div>  
<div class="row">
        <div class="col s12 m12 l12">
            {{movieobj.storyline}}
        </div>
    </div> 
    </div> 




<style>
  .card-pad,
  .card-content {
    background-color: white;
  }

  .card-title {
    background-color: #333;
    height: 90px;
    padding: 15px 0px 0px 10px;
    color:white;
    margin-left: 12px;
  }

  .card-content {
    width: auto;
    height: 227px;
  }

  h1 {
    padding-top: 20px;
  }
  container iframe{
    position: absolute;
    top: 0;
    left: 0;
    width: 80% !important;
    height: 79% !important;
}

  
</style>
<script>
        $(document).ready(function(){
            $('.carousel').carousel();
          });
</script>
{% endblock %}